import { DataTypes } from 'sequelize';
import { sequelize } from '../config/db.js';

// Farm-specific advisory generated by the rule engine (spec Part G).
// `sourceData` snapshots the inputs used (indices, weather, crop age) so the
// advice is auditable; wording follows the agronomic-safety rule — indicators,
// not diagnoses (spec G-35).
export const Advisory = sequelize.define(
  'Advisory',
  {
    id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
    farmId: { type: DataTypes.INTEGER, allowNull: false },
    cropSeasonId: { type: DataTypes.INTEGER },
    ruleId: { type: DataTypes.INTEGER },
    category: { type: DataTypes.STRING(40), allowNull: false },
    severity: {
      type: DataTypes.STRING(20),
      allowNull: false,
      defaultValue: 'information',
      validate: { isIn: [['information', 'normal', 'attention', 'warning', 'critical']] },
    },
    title: { type: DataTypes.STRING(200), allowNull: false },
    message: { type: DataTypes.TEXT, allowNull: false },
    status: { type: DataTypes.STRING(20), defaultValue: 'open', validate: { isIn: [['open', 'acknowledged', 'resolved']] } },
    generatedAt: { type: DataTypes.DATEONLY, allowNull: false, defaultValue: DataTypes.NOW },
    sourceData: { type: DataTypes.JSONB },
  },
  {
    tableName: 'advisories',
    indexes: [{ fields: ['farmId', 'status'], name: 'advisories_farm_status' }],
  }
);
